name: Docker Build and Push to Docker Hub

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t logicgod007/cogneotech:${{ github.sha }} .
        docker tag logicgod007/cogneotech:${{ github.sha }} logicgod007/cogneotech:latest

    - name: Push Docker image
      run: |
        docker push logicgod007/cogneotech:${{ github.sha }}
        docker push logicgod007/cogneotech:latest